/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: 'https://sangetaj.com',
  generateRobotsTxt: false, // We maintain our own robots.txt in /public
  changefreq: 'weekly',
  priority: 0.7,
  sitemapSize: 5000,
  exclude: ['/api/*'],
  additionalPaths: async (config) => [
    await config.transform(config, '/'),
    await config.transform(config, '/collections'),
    await config.transform(config, '/collections/sang-e-zafar'),
    await config.transform(config, '/collections/sang-e-nakhoda'),
    await config.transform(config, '/collections/sang-e-sultan'),
    await config.transform(config, '/collections/sang-e-amir'),
    await config.transform(config, '/bespoke'),
    await config.transform(config, '/corporate'),
    await config.transform(config, '/heritage'),
    await config.transform(config, '/journal'),
    await config.transform(config, '/contact'),
    await config.transform(config, '/journal/what-is-makrana-marble'),
    await config.transform(config, '/journal/how-to-commission-a-bespoke-marble-showpiece'),
    await config.transform(config, '/journal/luxury-marble-corporate-gifts-gulf'),
    await config.transform(config, '/journal/makrana-marble-vs-carrara-marble'),
    await config.transform(config, '/journal/gulf-maritime-heritage-dhow'),
    await config.transform(config, '/journal/why-makrana-marble-has-never-yellowed'),
    await config.transform(config, '/journal/why-makrana-marble-has-never-been-replicated'),
    await config.transform(config, '/journal/the-language-of-gifting-in-the-gulf'),
    await config.transform(config, '/journal/from-the-quarry-to-the-atelier'),
    await config.transform(config, '/journal/the-dhow-in-gulf-heritage'),
    await config.transform(config, '/journal/what-to-place-in-a-majlis'),
    await config.transform(config, '/journal/how-to-commission-a-marble-showpiece'),
    await config.transform(config, '/journal/why-marble-gets-better-with-time'),
  ],
}
